### NUMPY INDEXING TUTORIAL
- Replace NumPy array elements that doesn’t satisfy the given condition

In [1]:
import numpy as np
np.random.seed(101)

In [2]:
arr = np.arange(1, 10)

print('Original array: %s'%arr)
print("Replace values that aren't graeater than 4 with 0")

arr[~(arr > 4)] = 0

print('Array with values replaced: %s'%arr)

Original array: [1 2 3 4 5 6 7 8 9]
Replace values that aren't graeater than 4 with 0
Array with values replaced: [0 0 0 0 5 6 7 8 9]


- Return the indices of elements where the given condition is satisfied

In [3]:
arr = np.array([0, 4, 1, 0, 2, 0])
zero_idx = np.where(arr == 0)

print('The array %s\nhas values 0 at index %s'%(arr, zero_idx[0]))

The array [0 4 1 0 2 0]
has values 0 at index [0 3 5]


- Replace NaN values with average of columns

In [4]:
arr = np.array([[0, 5, 1, 3, 4],
                [np.nan, 2, 4, 7, np.nan],
                [2, 3, 1, 10, 11],
                [0, 2, 5, np.nan, 12]])

means = np.nanmean(arr, axis=0)
idx = np.where(np.isnan(arr))

print('The array:\n%s\nhas NaN values at colums %s'%(arr, idx[1]))
print('The mean values of the colums are: %s'%means)

arr[idx] = means[idx[1]]

print('The resulting array is:\n%s'%arr)


The array:
[[ 0.  5.  1.  3.  4.]
 [nan  2.  4.  7. nan]
 [ 2.  3.  1. 10. 11.]
 [ 0.  2.  5. nan 12.]]
has NaN values at colums [0 4 3]
The mean values of the colums are: [0.66666667 3.         2.75       6.66666667 9.        ]
The resulting array is:
[[ 0.          5.          1.          3.          4.        ]
 [ 0.66666667  2.          4.          7.          9.        ]
 [ 2.          3.          1.         10.         11.        ]
 [ 0.          2.          5.          6.66666667 12.        ]]


- Replace negative value with zero in numpy array

In [5]:
arr = np.array([[9, 5, 1, 3, 4],
                [-4, 2, 4, 7, -12],
                [2, 3, 1, -2, 11],
                [5, 2, 5, -11, 12]])

print('Replace negative value with 0:\n%s\n'%arr)
arr[arr < 0] = 0

print('Result:\n%s'%arr)

Replace negative value with 0:
[[  9   5   1   3   4]
 [ -4   2   4   7 -12]
 [  2   3   1  -2  11]
 [  5   2   5 -11  12]]

Result:
[[ 9  5  1  3  4]
 [ 0  2  4  7  0]
 [ 2  3  1  0 11]
 [ 5  2  5  0 12]]


- Get values of an NumPy array at certain index positions

In [6]:
arr = np.random.randint(1, 20, (4, 3))
row = np.random.randint(0, 4)
col = np.random.randint(0, 3)

value = arr[row, col]
full_row = arr[row, :]
full_col = arr[:, col]

print('Array:\n%s\n'%arr)
print('The row at index %s is: %s'%(row, full_row))
print('The column at index %s is: %s'%(col, full_col))
print('The value at index %s %s is: %s'%(row, col, value))

Array:
[[12 18  7]
 [12 16 10]
 [14  9  5]
 [ 9  1 15]]

The row at index 1 is: [12 16 10]
The column at index 0 is: [12 12 14  9]
The value at index 1 0 is: 12


- Find indices of elements equal to zero in a NumPy array

In [7]:
arr = np.random.randint(0, 4, (4, 3))

idx = np.where(arr == 0)

formatted_idx = np.column_stack((idx[0], idx[1]))
print('Array:\n%s\n'%(arr))
print('Indices of elements equals to zero :\n%s\n'%(formatted_idx))

Array:
[[1 0 1]
 [3 3 2]
 [0 3 1]
 [3 3 2]]

Indices of elements equals to zero :
[[0 1]
 [2 0]]



- How to Remove columns in Numpy array that contains non-numeric values

In [8]:
arr = np.array([[1, 4, np.nan, 6],
                [2, np.nan, 5, 3]])

colums_idx = ~np.isnan(arr).any(axis=0)
result = arr[:, colums_idx]

print('Array:\n%s\n'%arr)
print('After removing columns containing NaN:\n%s'%result)

Array:
[[ 1.  4. nan  6.]
 [ 2. nan  5.  3.]]

After removing columns containing NaN:
[[1. 6.]
 [2. 3.]]


- How to access different rows of a multidimensional NumPy array

In [9]:
arr = np.random.randint(0, 10, (5, 5))
row_idx =  np.random.randint(5)
row_values = arr[row_idx, :]

print('The row at index %s of the array:\n%s\n\nis: %s'%(row_idx, arr, row_values))

The row at index 2 of the array:
[[8 9 3 7 0]
 [9 7 9 8 4]
 [3 3 7 4 8]
 [7 6 9 4 2]
 [7 7 7 0 4]]

is: [3 3 7 4 8]


- Get row numbers of NumPy array having element larger than X

In [10]:
X = 7
arr = np.random.randint(0, 10, (5, 5))
row_idx, = np.where(np.any(arr > X, axis=1))

print('Array:\n%s\n'%arr)
print('Indices of rows containing a value larger than %s:\n%s'%(X, row_idx))

Array:
[[1 8 3 1 8]
 [4 3 2 3 3]
 [7 4 8 6 3]
 [7 6 5 6 9]
 [2 2 1 3 3]]

Indices of rows containing a value larger than 7:
[0 2 3]


- Get filled the diagonals of NumPy array

In [11]:
value = 1
arr = np.zeros((4, 4))
# Fill diagonal starting up
np.fill_diagonal(arr, value)
# Fill diagonal starting down
np.fill_diagonal(arr[::-1,:], value)

print('Array:\n%s\n'%arr)

Array:
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]



- Check elements present in the NumPy array

In [12]:
arr = np.random.randint(0, 10, (5, 5))

values = [11, 5, 3, 12]

print('A =\n%s\n'%arr)
for val in values:
    print('Is %s in A? %s'%(val, val in arr))

A =
[[3 4 5 9 5]
 [8 3 6 8 7]
 [5 7 5 4 4]
 [7 3 2 3 2]
 [9 3 5 6 6]]

Is 11 in A? False
Is 5 in A? True
Is 3 in A? True
Is 12 in A? False


- Combined array index by index

In [13]:
arr1 = np.random.randint(1, 10, 3)
arr2 = np.random.randint(1, 10, 3)

combined = np.vstack((arr1, arr2)).flatten('F')

print('Array#1:\n%s\n\nArray#2:\n%s\n'%(arr1, arr2))
print('Combination:\n%s'%combined)

Array#1:
[6 6 2]

Array#2:
[8 5 8]

Combination:
[6 8 6 5 2 8]
