### NUMPY RANDOM
- Create a Numpy array with random values

In [1]:
import numpy as np
np.random.seed(101)

In [2]:
arr = np.random.rand(5)
print('Random array:\n%s'%arr)

Random array:
[0.51639863 0.57066759 0.02847423 0.17152166 0.68527698]


- Choose elements from the list with different probability using NumPy

In [3]:
list_ = [1, 2, 3, 4, 5]
prob = [.1, .2, .2, .4, .1] # Defines probability for every number in the array of choice

choiches = np.random.choice(list_, 5, p=prob)

print('List: %s'%list_)
print('Probablilty for every element in List: %s'%prob)
print('Five random choices using the given probability %s'%choiches)

List: [1, 2, 3, 4, 5]
Probablilty for every element in List: [0.1, 0.2, 0.2, 0.4, 0.1]
Five random choices using the given probability [4 3 4 4 2]


-  Getting weighted random choice in Python

In [4]:
from random import choices, seed
seed(101)

In [5]:
weights = [50, 25, 60, 40, 10]
choices_ = choices(list_, weights=weights, k=5)

print('List: %s'%list_)
print('Weight for every element in List: %s'%weights)
print('Five random choices using the given weights %s'%choices_)

List: [1, 2, 3, 4, 5]
Weight for every element in List: [50, 25, 60, 40, 10]
Five random choices using the given weights [3, 1, 5, 4, 3]


- Generate Random Numbers From The Uniform Distribution using NumPy

In [6]:
low, high = (0, 5)
uniform = np.random.uniform(low, high, 6)

print('Array of random values from a uniform distribution ranging from %s to %s:\n%s'%(low, high, uniform))

Array of random values from a uniform distribution ranging from 0 to 5:
[2.77113796 1.76065977 0.90946201 3.92800881 4.82741611 1.16176831]


- Getting Random Elements form geometric distribution

In [7]:
geom = np.random.geometric(p=.13, size=10)

print('Array of random elements from a geometric distribution:\n%s'%geom)

Array of random elements from a geometric distribution:
[ 1  7 10  3  9  6  1  2  2 38]


- Get Random elements from Laplace distribution

In [8]:
peak = 2
laplace = np.random.laplace(loc=peak, size=10)

print('Ten random element from Laplace distribution with peak at %s:\n%s'%(peak, laplace))

Ten random element from Laplace distribution with peak at 2:
[2.0422092  2.17147547 2.63419571 2.08765545 3.75046657 2.95669693
 1.78432308 1.6637559  4.36184084 1.62496199]


- Return a Matrix of random values from a uniform distribution

In [9]:
low, high = (5, 20)
uniform = np.random.uniform(low, high, (4,4))

print('Matrix of random values from a uniform distribution ranging from %s to %s:\n%s'%(low, high, uniform))

Matrix of random values from a uniform distribution ranging from 5 to 20:
[[17.97649724 17.45416568 13.07242174 18.83704059]
 [ 6.4571972   6.5427124  15.52260944 18.35719804]
 [ 7.39340451  9.13358817 15.08737294  7.46454686]
 [15.52056705 12.31452833 15.21016652 12.82322288]]


- Return a Matrix of random values from a Gaussian distribution

In [10]:
center = 5
gaussian = np.random.normal(loc=center, size=(5, 2))

print('Matrix of random values from a Gaussian distribution with mean at %s:\n%s'%(center, gaussian))

Matrix of random values from a Gaussian distribution with mean at 5:
[[4.0067365  5.1967995 ]
 [3.86335541 5.00036648]
 [6.02598415 4.8434021 ]
 [4.96842086 5.64982583]
 [7.15484644 4.38974114]]
