### SORTING AND SEARCHING WITH NUMPY
- Getting the indices of a sorted array using NumPy

In [1]:
import numpy as np
np.random.seed(101)

In [2]:
arr = np.random.randint(1, 9, 6)

sorted_idx = np.argsort(arr)

print('Array: %s'%arr)
print('Indices of sorted array: %s'%sorted_idx)
print('Sorted array: %s'%arr[sorted_idx])

Array: [8 4 2 7 8 8]
Indices of sorted array: [2 1 3 0 4 5]
Sorted array: [2 4 7 8 8 8]


- Finding the k smallest values of a NumPy array

In [3]:
k = 4
arr = np.random.randint(1, 9, 10)

sorted_arr = np.sort(arr)
small = sorted_arr[:k]

print('Original array: %s'%arr)
print('Sorted array: %s'%sorted_arr)
print('%s lowest values: %s'%(k, small))

Original array: [6 4 8 2 6 1 5 8 1 6]
Sorted array: [1 1 2 4 5 6 6 6 8 8]
4 lowest values: [1 1 2 4]


- Getting the n-largest values of an array using NumPy

In [4]:
n = 4
arr = np.random.randint(1, 9, 10)

sorted_arr = np.sort(arr)
larg = sorted_arr[-n:]

print('Original array: %s'%arr)
print('Sorted array: %s'%sorted_arr)
print('%s largest values: %s'%(n, larg))

Original array: [5 5 1 7 6 5 6 1 2 4]
Sorted array: [1 1 2 4 5 5 5 6 6 7]
4 largest values: [5 6 6 7]


- Sorting the values in a matrix

In [5]:
arr = np.random.randint(1, 9, (3, 3))

sorted_cols = np.sort(arr, axis=0)
sorted_rows = np.sort(arr, axis=1)

print('Array:\n%s\n'%arr)
print('Column sort:\n%s\n'%sorted_cols)
print('Rows sort:\n%s'%sorted_rows)

Array:
[[8 3 1]
 [4 6 4]
 [4 3 5]]

Column sort:
[[4 3 1]
 [4 3 4]
 [8 6 5]]

Rows sort:
[[1 3 8]
 [4 4 6]
 [3 4 5]]


- Filter out integers from float numpy array

In [6]:
arr = np.array([1, 3, 0.2, 1.5, 4, 10.1])

int_arr = arr[arr == arr.astype(int)]
float_arr = arr[arr != arr.astype(int)]

print('Original array: %s'%arr)
print('Filtering out floats: %s'%int_arr)
print('Filtering out integers: %s'%float_arr)

Original array: [ 1.   3.   0.2  1.5  4.  10.1]
Filtering out floats: [1. 3. 4.]
Filtering out integers: [ 0.2  1.5 10.1]


- Find the indices into a sorted array

In [7]:
arr = np.array([3, 5, 7, 11, 13, 17, 19])

num = [2, 6, 15]
idx = np.searchsorted(arr, num)

print('Array: %s'%arr)
print('Values %s should be placed at index %s'%(num, idx))

Array: [ 3  5  7 11 13 17 19]
Values [2, 6, 15] should be placed at index [0 2 5]
