# NUMPY ARRAY TUTORIAL

- Create an empty and a full NumPy array

In [2]:
import numpy as np

In [3]:
empty = np.array([])
full = np.array([5, 9, 11, 25])
print(empty)
print(full)

[]
[ 5  9 11 25]


- Create a Numpy array filled with all zeros

In [5]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- Create a Numpy array filled with all ones

In [6]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


- Check whether a Numpy array contains a specified row

In [8]:
arr = np.array([[1,2,3],
                [5, 7, 11],
                [13, 15, 17]])

print(arr)
print([1, 2, 3] in arr.tolist())
print([1, 5, 13] in arr.tolist())

[[ 1  2  3]
 [ 5  7 11]
 [13 15 17]]
True
False


- Remove rows in a Numpy array that contains non-numeric values

In [9]:
n_arr = np.array([[1, 2, 4],
                    [np.nan, 5, 19],
                    [0, 9, 33]])
print('Given array:')
print(n_arr)
print('nan rows removed:')
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[ 1.  2.  4.]
 [nan  5. 19.]
 [ 0.  9. 33.]]
nan rows removed:
[[ 1.  2.  4.]
 [ 0.  9. 33.]]


- Remove single-dimensional entries from the shape of an array

In [10]:
arr = np.array([[[1, 2, 3], [55, 12, 78]]])
squeezed = np.squeeze(arr)

print('Imput array:')
print(arr)
print('Array shape:')
print(arr.shape)
print('Result:')
print(squeezed)
print('Result shape:')
print(squeezed.shape)

Imput array:
[[[ 1  2  3]
  [55 12 78]]]
Array shape:
(1, 2, 3)
Result:
[[ 1  2  3]
 [55 12 78]]
Result shape:
(2, 3)


- Find the number of occurrences of a sequence in a NumPy array

In [13]:
arr = np.array([[1, 2, 3, 4],
                [6, 8, 1, 2],
                [1, 2, 5, 6]])
reps = repr(arr).count('1, 2')

print('Repetitions of 1, 2 in:\n%s'%arr)
print(reps)

Repetitions of 1, 2 in:
[[1 2 3 4]
 [6 8 1 2]
 [1 2 5 6]]
3


- Find the most frequent value in a NumPy array

In [15]:
arr = [5, 2, 5, 2, 6, 2, 5, 7, 2, 4, 2]
most_frequent = np.bincount(arr).argmax()

print(arr)
print('Most frequent value is %s'%most_frequent)

[5, 2, 5, 2, 6, 2, 5, 7, 2, 4, 2]
Most frequent value is 2


- Combining a one and a two-dimensional NumPy Array

In [16]:
arr_1d = np.array([1, 2, 3, 4])

arr_2d = np.array([[6, 2, 1, 6], 
                   [9, 8, 7, 6]])

combined = np.vstack((arr_1d, arr_2d))

print('One dimensional: %s'%arr_1d)
print('Two dimensional:\n%s'%arr_2d)
print('Combined:\n%s'%combined)

One dimensional: [1 2 3 4]
Two dimensional:
[[6 2 1 6]
 [9 8 7 6]]
Combined:
[[1 2 3 4]
 [6 2 1 6]
 [9 8 7 6]]


-  Build an array of all combinations of two NumPy arrays

In [21]:
arr1 = np.array([5, 6])
arr2 = np.array([1, 2])

combined = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1, len(arr1))

print('Array 1: %s'%arr1)
print('Array 2: %s'%arr2)
print('Combinations:\n%s'%combined)

Array 1: [5 6]
Array 2: [1 2]
Combinations:
[[5 1]
 [5 2]
 [6 1]
 [6 2]]


- Add a border around a NumPy array

In [23]:
arr = np.ones((4, 4))
padded = np.pad(arr, pad_width=1)

print('Original:\n%s'%arr)
print('Padded:\n%s'%padded)

Original:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Padded:
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


- Compare two NumPy arrays

In [24]:
a = np.array([1, 5, 9, 12])
b = np.array([6, 3, 1, 11])
print('a = %s'%a)
print('b = %s'%b)
print('a > b')
print(np.greater(a, b))
print('a >= b')
print(np.greater_equal(a, b))
print('a < b')
print(np.less(a, b))
print('a <= b')
print(np.less_equal(a, b))
print('a == b')
print(a == b)

a = [ 1  5  9 12]
b = [ 6  3  1 11]
a > b
[False  True  True  True]
a >= b
[False  True  True  True]
a < b
[ True False False False]
a <= b
[ True False False False]
a == b
[False False False False]


- Check whether specified values are present in NumPy array

In [26]:
arr = np.array([5, 6, 9, 12])
print('Array: %s'%arr)
print('is 4 in array? %s'%(4 in arr))
print('is 9 in array? %s'%(9 in arr))
print('is 7 in array? %s'%(7 in arr))

Array: [ 5  6  9 12]
is 4 in array? False
is 9 in array? True
is 7 in array? False


- Get all 2D diagonals of a 3D NumPy array

In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[0, 4, 2], [1, 7, 8], [9, 10, 11]],
                [[4, 2, 1], [9, 1, 2], [0, 7, 0]]])

diag_array = np.diagonal(arr, axis1=1, axis2=2)

print('Array:\n%s'%arr)
print('2D diagonals:\n%s'%diag_array)

Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 0  4  2]
  [ 1  7  8]
  [ 9 10 11]]

 [[ 4  2  1]
  [ 9  1  2]
  [ 0  7  0]]]
2D diagonals:
[[ 1  5  9]
 [ 0  7 11]
 [ 4  1  0]]


- Flatten a Matrix in Python using NumPy

In [30]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [4,3,2,1]])

# Equivalent to: arr.ravel()
flat = arr.flatten()

print('Original:\n%s'%arr)
print('Flat: %s'%flat)

Original:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
Flat: [1 2 3 4 5 6 7 8 4 3 2 1]


- Flatten a 2d numpy array into 1d array

In [32]:
# The code in the above cell will also work for this task
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [4,3,2,1]])

flat_shape = arr.shape[0] * arr.shape[1] 
flat = arr.reshape(flat_shape)

print('Original:\n%s'%arr)
print('Flat: %s'%flat)

Original:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
Flat: [1 2 3 4 5 6 7 8 4 3 2 1]


- Move axes of an array to new positions

In [37]:
arr1 = np.array([[[1], [2]], [[3], [4]], [[7], [1]]])
arr2 = np.moveaxis(arr1, 0, 2)

print('Array1:\n%s\n'%arr1)
print('Array2:\n%s\n'%arr2)
print('Shape1: %s\t\tShape2: %s'%(arr1.shape, arr2.shape))

Array1:
[[[1]
  [2]]

 [[3]
  [4]]

 [[7]
  [1]]]

Array2:
[[[1 3 7]]

 [[2 4 1]]]

Shape1: (3, 2, 1)		Shape2: (2, 1, 3)


- Interchange two axes of an array

In [38]:
arr1 = np.array([[[1, 5], [2, 3], [9, 10]], 
                 [[3, 1], [4, 9], [2, 11]], 
                 [[7, 2], [1, 2], [6, 6]],
                 [[3, 1], [4, 9], [2, 11]]])

arr2 = np.swapaxes(arr1, 0, 2)

print('Array1:\n%s\n'%arr1)
print('Array2:\n%s\n'%arr2)
print('Shape1: %s\t\tShape2: %s'%(arr1.shape, arr2.shape))

Array1:
[[[ 1  5]
  [ 2  3]
  [ 9 10]]

 [[ 3  1]
  [ 4  9]
  [ 2 11]]

 [[ 7  2]
  [ 1  2]
  [ 6  6]]

 [[ 3  1]
  [ 4  9]
  [ 2 11]]]

Array2:
[[[ 1  3  7  3]
  [ 2  4  1  4]
  [ 9  2  6  2]]

 [[ 5  1  2  1]
  [ 3  9  2  9]
  [10 11  6 11]]]

Shape1: (4, 3, 2)		Shape2: (2, 3, 4)


- NumPy – Fibonacci Series using Binet Formula

In [41]:
fib_size = 12

sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

a = np.arange(1, fib_size + 1)

# np.rint rounds numbers to the nearest integer
fib = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print('Fibonacci sequence of size %s:\n%s'%(fib_size, fib))

Fibonacci sequence of size 12:
[  1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144.]


- Count the number of non-zero values in the array

In [48]:
arr = np.array([[0, 10, 11, 12], [22, 4, 0, 0]])
non_zero = np.count_nonzero(arr)

print('Array:\n%s'%arr)
print('# of values different to 0: %s'%non_zero)

Array:
[[ 0 10 11 12]
 [22  4  0  0]]
# of values different to 0: 5


- Count the number of elements along a given axis

In [50]:
arr = np.array([[1, 2, 3],
                [4, 6, 8]])

print('Array:\n%s'%arr)
print('# of rows along x-axis: %s'%np.size(arr, axis=0))
print('# of cols along y-axis: %s'%np.size(arr, axis=1))

Array:
[[1 2 3]
 [4 6 8]]
# of rows along x-axis: 2
# of cols along y-axis: 3


- Trim the leading and/or trailing zeros from a 1-D array

In [51]:
arr = np.array((0, 0, 0, 5, 7, 0, 6, 9, 0, 10, 0, 0))
trimmed = np.trim_zeros(arr)

print('Original array: %s'%arr)
print('trimmed array: %s'%trimmed)

Original array: [ 0  0  0  5  7  0  6  9  0 10  0  0]
trimmed array: [ 5  7  0  6  9  0 10]


- Change data type of given numpy array

In [4]:
arr = np.array([5.4, 2.2, 1.3, 1.5])
arr_int = arr.astype(np.uint)

print('Original Array (%s): %s'%(arr.dtype, arr))
print('Original Array (%s): %s'%(arr_int.dtype, arr_int))

Original Array (float64): [5.4 2.2 1.3 1.5]
Original Array (uint64): [5 2 1 1]


- Reverse a numpy array


In [5]:
arr = np.array([5, 4, 3, 2, 1, 0])
rev = arr[::-1]

print('Original: %s'%arr)
print('Reversed: %s'%rev)

Original: [5 4 3 2 1 0]
Reversed: [0 1 2 3 4 5]


- Read-only Numpy array

In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr.setflags(write=False)

try:
    arr[1] = 0
except ValueError:
    print('[!] Array %s is read-only'%arr)


[!] Array [1 2 3 4 5] is read-only
