### NUMPY LINEAR ALGEBRA TUTORIAL
- Find a matrix or vector norm using NumPy

In [1]:
import numpy as np
np.random.seed(101)

In [2]:
vect = np.array([[2, 4, 6], 
                 [6, 9, 1]])

norm = np.linalg.norm(vect)

print('The norm of\n%s\n\n is %s'%(vect, norm))

The norm of
[[2 4 6]
 [6 9 1]]

 is 13.19090595827292


- Calculate the QR decomposition of a given matrix using NumPy

In [3]:
arr = np.random.randint(1, 5, (3, 3))

q, r = np.linalg.qr(arr)

print('Matrix:\n%s\n'%arr)
print('QR decomposition:\nQ =\n%s\nR =\n%s'%(q, r))

Matrix:
[[4 4 2]
 [3 4 4]
 [2 4 4]]

QR decomposition:
Q =
[[-0.74278135  0.53066863  0.40824829]
 [-0.55708601 -0.15161961 -0.81649658]
 [-0.37139068 -0.83390785  0.40824829]]
R =
[[-5.38516481 -6.68503217 -5.19946947]
 [ 0.         -1.8194353  -2.88077257]
 [ 0.          0.         -0.81649658]]


- Compute the condition number of a given matrix using NumPy

In [4]:
arr = np.random.randint(1, 5, (3, 3))

cond_number = np.linalg.cond(arr)

print('Matrix:\n%s\n'%arr)
print('The condition number of the matrix is %s'%cond_number)

Matrix:
[[2 2 1]
 [1 4 1]
 [2 1 1]]

The condition number of the matrix is 55.50924626227031


- Compute the eigenvalues and right eigenvectors of a given square array using NumPy

In [5]:
arr = np.random.randint(1, 5, (3, 3))

vals, vect = np.linalg.eig(arr)

print('Matrix:\n%s\n'%arr)
print('Eigenvalues of the matrix:\n%s\n'%vals)
print('Eigenvectors of the matrix:\n%s\n'%vect)

Matrix:
[[1 3 2]
 [1 2 1]
 [2 4 4]]

Eigenvalues of the matrix:
[ 6.4902922  -0.35596772  0.86567551]

Eigenvectors of the matrix:
[[-0.46337212 -0.93070544 -0.21003498]
 [-0.28970144  0.35013257 -0.53579896]
 [-0.837472    0.10580441  0.81780486]]



- Calculate the Euclidean distance using NumPy

In [6]:
vect1 = np.random.randint(1, 5, 3)
vect2 = np.random.randint(1, 5, 3)

distance = np.linalg.norm(vect1-vect2)

print('V = %s\nW = %s\n'%(vect1, vect2))
print('The distance between V and W is %s'%distance)

V = [3 1 4]
W = [2 4 4]

The distance between V and W is 3.1622776601683795
